### PR TITLE
Update bacon.R

### PR DESCRIPTION
**Pull request by krferrier**
Include variables for setting the global seed (necessary for controlling results between separate bacon calls when the bacon function is run serially) and for setting the parallel seed (necessary for controlling the results between separate bacon calls when the bacon function is run in parallel and the globalSeed=NULL). These variables are set to 42 by default, but can be changed to other integers or to NULL to allow the default randomization. In the instance that globalSeed=NULL and parallelSeed != NULL and the input statistics are a matrix, randomization will occur across parallel processes within a bacon call but will reproduce the same results across separate calls to bacon (which could be handy for calculating average estimated inflation or bias, or confidence intervals of either metric). If globalSeed != NULL and the input statistics are a matrix, then the results will be the same across parallel processes within a bacon call and across separate calls to bacon regardless of the parallelSeed value.

### CODE REVIEW

**Comment by krferrier** [comment]
I wasn't sure if including variables for both the global seed and the BiocParallel RNGseed would be too confusing for the average user. If you think it is, setting the global seed alone controls the random number generation of both the serial and parallel bacon calls and I can submit a new commit that only includes modifications for the global seed. I also wasn't sure if it would be preferable to have the default seed values be an integer (setting a seed) or NULL (not setting a seed).

**Comment by mvaniterson** [comment]
Dear Kendra, would it a be possible to also add some documentation? 

For example, your description could go the documentation section
 _globalSeed = 42, # if set to NULL, randomization will occur for sequential and parallel bacon calls
 parallelSeed = 42){ # if input statistics are a matrix and globalSeed=NULL, setting parallelSeed=NULL will allow randomization across parallel processes within a bacon call and across separate calls to bacon._
It would also be nice if we could add a subsection to the vignette describing the situation when you need this and give a small example.

Furthermore, the PR looks good!

Regards, 
Maarten

**Comment by krferrier** [comment]
Hi Maarten, I'm still pretty new to making packages (this is the first one I've even contributed to!), so, I think that I added the comments to the documentation section in the bacon.R file correctly, but I'm not entirely sure and wasn't able to regenerate the .Rd files correctly to check myself. I also added a section to the vignettes describing a use case for setting globalSeed to NULL and using the default parallelSeed. I think a new object would need to be made (similar to the meta object) in order to use the plotting functions with the example case I used. I can open a separate issue/PR for that if you think that's necessary.  

I've also updated the plotting functions traces, posteriors, and fit to use ggplot instead of base R. The updated versions would additionally require the `reshape2` library. Let me know if you'd like me make a PR for those changes too.

**Comment by mvaniterson** [comment]
Hi Kendra, the documentation was fine I've updated data Rd-files. Furthermore, I made a few changess to the section you added to the vignette mostly to make it more clear how a user could use this part. If you think I'm missing something please let me known! I needed to reduce the number of replicates because the package including vignette build must be under a few minutes. 

Did you publish your work on the bacon CI setup, we could add it as reference?

**Comment by krferrier** [comment]
Hi Maarten, the changes to the CI section look fine to me. The only thing potentially worth adding is that a user should do at minimum 30 replicates for a CI. But, one would also hope that if someone is familiar with calculating CI they should know that already. 
I have not published work using the bacon CI setup-- I didn't realize that potential functionality until I figured out the RNG was happening in two places, which wasn't until ~2 weeks ago. I will be submitting an EWAS for publication soon though and could pretty easily incorporate that and send the reference as soon as I have one.

**Comment by mvaniterson** [comment]
_The only thing potentially worth adding is that a user should do at minimum 30 replicates for a CI._ 

Thanks this is indeed useful!

I assume that bacon, with your contribution, will be available when Bioc  3.19 is release beginning of May.

Success with your publication!

Cheers, 
Maarten

**Pull request merged**
